#Create a simple playbook that installs Nginx on a target server and ensures the service is running.
- name: install nginx
  hosts: ubuntu
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.apt:
      name: nginx
      state: present
